[package]
name = "cli-agent"
version.workspace = true
edition.workspace = true

[dependencies]
bob-adapters = { path = "../../crates/bob-adapters" }
bob-runtime = { path = "../../crates/bob-runtime" }
clap = { workspace = true, features = ["derive"] }
config = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
